# Generated by Django 3.2.5 on 2021-08-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('age', models.PositiveSmallIntegerField()),
                ('date_of_birth', models.DateField()),
                ('profile', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('class_name', models.CharField(max_length=15)),
                ('student_id', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=14)),
                ('phone_Number', models.PositiveIntegerField()),
                ('registration_number', models.PositiveSmallIntegerField()),
                ('big_sister', models.CharField(max_length=10)),
                ('mentor_name', models.CharField(max_length=10)),
                ('room_number', models.CharField(max_length=12)),
                ('regions', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=15)),
                ('county', models.CharField(max_length=12)),
                ('emergency_Contact', models.PositiveIntegerField()),
            ],
        ),
    ]
